[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixpkgsArchive = "23f9169c4ccce521379e602cc82ed873a1f1b52b"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["VITE_API_URL=https://dt-server.wonderprotect.net/api npm run build"]

[start]
cmd = "sh scripts/start.sh"
